#!/bin/bash
##1. this script run a top 1000 portscan
##2. It then version enumerates the ports found
##3. If port 80 is found it runs a nikto and ffuf scan
##4. Runs a full port scan on the ip
##             V1.0
##prereqs
##nmap,ffuf,nikto

echo "##################################"
echo "#          Recon Script          #"
echo "#                                #"
echo -e "#          By \e[1;31m Dalemazza\e[0m         #"
echo "#                                #"
echo "#  Basic port scan, Enumerates   #"
echo "#    Versions, If port 80 found  #"
echo "#    runs nikto and ffuf scans,  #"
echo "#    Then runs Full port scan    #"
echo "#              v.1.1             #"
echo "##################################"
set -u
###Ip input
echo "- - - - - - - - - - - - - - - - -"
echo "           Input the IP          "
echo "- - - - - - - - - - - - - - - - -"
read -r ip
start=$SECONDS  ####timer
########################################
userpwd=$(cd && pwd) > /dev/null #######getting userpwd and storing it as user variable
recon_dir=$userpwd/reports/ ########seting recon dir
######making dir
make_dir="mkdir $recon_dir$ip"recon"" ######making recon dir
###if statement to check if dir already exists, if not makes it
if [ ! -d "$userpwd/reports" ];then
			mkdir $userpwd/reports > /dev/null      ######needs hiding
fi
echo "- - - - - - - - - - - - - - - - -"
echo "        Making Directory         "
echo "- - - - - - - - - - - - - - - - -"
#$make_dir
###if statement to check if dir already exists, if not makes it
if [ ! -d "$recon_dir/$ip"recon"" ];then
			mkdir $recon_dir$ip"recon" > /dev/null   ######
fi


echo -e "\e[1;32m               DONE       \e[0m"
working_dir=$userpwd/reports/$ip'recon'/
#######################################
###Nmap Basc scan top 1000 ports

nmap_basic="sudo nmap -T4 -oN "$working_dir"nmap_basic $ip"
###does the nmap scan and sends it to dev/null to hide it form output

$nmap_basic > /dev/null

echo "- - - - - - - - - - - - - - - - -"
echo "     Starting Nmap Basic Scan    "
echo "- - - - - - - - - - - - - - - - -"
nmap_basic_results=$userpwd/reports/$ip'recon'/nmap_basic

###until loop checks for "Nmap done" until it finishes then sends DONE
until grep -q "Nmap done" "$nmap_basic_results";
	do echo "             Scanning"
	sleep 5
done
echo -e "\e[1;32m               DONE       \e[0m"
####################################
###Grabbing ports from results.
awk '/open/{print $1}' "$working_dir"nmap_basic | awk -F '/' '{print $1}' > "$working_dir"ports.txt
###sort ports into ports into format for nmap
ports=$working_dir"ports.txt"
########################################
###Nmap scan versions for ports found open######
###
nmap_versions="sudo nmap -A -p $(tr '\n' , <"$ports") -oN "$working_dir"nmap_versions "$ip""
nmap_versions_results=$userpwd/reports/$ip'recon'/nmap_versions

echo "- - - - - - - - - - - - - - - - -"
echo "       Enumerating Verions       "
echo "- - - - - - - - - - - - - - - - -"
$nmap_versions > /dev/null &
sleep 2
until grep -q "Nmap done" "$nmap_versions_results";
	do echo  -e "\e[1;36m             Scanning \e[0m"
	sleep 15
done
echo -e "\e[1;32m               DONE       \e[0m"
######################################
###ffuf and nikto scans if port 80 is found in ports.txt

if cat "$ports" | grep "80" > /dev/null;
			then
					echo "- - - - - - - - - - - - - - - - -"
						echo "          Port 80 found          "
						echo "- - - - - - - - - - - - - - - - -"
						echo "          Nikto running          "
						echo "- - - - - - - - - - - - - - - - -"
						echo  -e "\e[1;36m             Scanning \e[0m"
						nikto -h "$ip" -output "$working_dir"nikto.txt > /dev/null
						echo -e "\e[1;32m               DONE       \e[0m"
						echo "- - - - - - - - - - - - - - - - -"
						echo "           ffuf Running          "
						echo "- - - - - - - - - - - - - - - - -"
						echo  -e "\e[1;36m             Scanning \e[0m"
						ffuf -u http://"$ip"/FUZZ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -c  -o "$working_dir"ffuf -of html -e '.txt,.html,.php,.pdf,.zip,.doc,.js' > /dev/null
						echo -e "\e[1;32m               DONE       \e[0m"
###Full port scan######
						nmap_full_results1=$userpwd/reports/$ip'recon'/nmap_full
						echo "- - - - - - - - - - - - - - - - -"
						echo "         Full Port Scan          "
						echo "- - - - - - - - - - - - - - - - -"
						echo  -e "\e[1;36m             Scanning \e[0m"
						sudo nmap -T4 -p- -oN "$working_dir"nmap_full $ip > /dev/null &
						sleep 2
						until grep -q "Nmap done" "$nmap_full_results1";
							do echo  -e "\e[1;36m             Scanning \e[0m"
							sleep 30
							done
						awk '/open/{print $1}' "$working_dir"nmap_full | awk -F '/' '{print $1}' > "$working_dir"fullports.txt #####makes full ports.txt
						fullports=$working_dir"fullports.txt"   ######fullport scan location
						echo -e "\e[1;32m               DONE       \e[0m"
						echo -e "\e[1;33m          Recon Complete \e[0m"
						end=$SECONDS
						duration=$(( end - start ))
						######show if new ports are found.
						sleep 30
						if cmp -s "$fullports" "$ports"; then
												echo -e "\e[1;32m        No new ports found! \e[0m"
						else

									echo -e "\e[1;92m          NEW PORTS FOUND \e[0m"
									diff $ports $fullports | grep ">" > "$working_dir"newports.txt && cat "$working_dir"newports.txt
						fi

						echo -e "\e[1;33m     Scan took $duration to complete \e[0m"
						echo -e "\e[1;33mReport written to $working_dir \e[0m"

	else
		nmap_full_results1=$userpwd/reports/$ip'recon'/nmap_full
		echo "- - - - - - - - - - - - - - - - -"
		echo "        Port 80 not found        "
		echo "          Full Port Scan         "
		echo "- - - - - - - - - - - - - - - - -"
		echo  -e "\e[1;36m             Scanning \e[0m"
		sudo nmap -T4 -p- -oN "$working_dir"nmap_full $ip > /dev/null &
		sleep 2
		until grep -q "Nmap done" "$nmap_full_results1";
			do echo  -e "\e[1;36m             Scanning \e[0m"
			sleep 30
			done
		echo -e "\e[1;32m               DONE       \e[0m"
		echo -e "\e[1;33m          Recon Complete \e[0m"
		end=$SECONDS
		duration=$(( end - start ))
		#sleep 30
		awk '/open/{print $1}' "$working_dir"nmap_full | awk -F '/' '{print $1}' > "$working_dir"fullports.txt #####makes full ports.txt
		fullports1=$working_dir"fullports.txt"  ########set fulllports1 location
		ports1=$working_dir"ports.txt"   ##########basicports1 location

		if cmp -s "$fullports1" "$ports1"; then
								echo -e "\e[1;32m        No new ports found! \e[0m"
		else

					echo -e "\e[1;92m          NEW PORTS FOUND \e[0m"
					diff $ports1 $fullports1 | grep ">" > "$working_dir"newports.txt && cat "$working_dir"newports.txt
		fi

		echo -e "\e[1;33m     Scan took $duration to complete \e[0m"
		echo -e "\e[1;33mReport written to $working_dir \e[0m"
fi
